query QueryStudentsTermin($eierInstitusjonsnummer: String!, $terminId: ID!, $after: String) {
    studenter(
        filter: { 
            eierOrganisasjonskode: $eierInstitusjonsnummer
            emnerITerminer: {
                termin: $terminId,
                harEmneStudierett: true
            }
        }  
        first: 1000
        after: $after
    ) {
        nodes {
            ...studentinfo
            programStudieretter {
                nodes {
                    kull {
                        id
                        erAktiv
                        skalEksporteresTilLms
                        lmsRomkode
                    }
                }
            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
        totalCount
    }
}
